name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # roda todo dia às 12h UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Upload prices.json
        uses: actions/upload-artifact@v4
        with:
          name: prices
          path: docs/prices.json

      - name: Upload Arena debug HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: arena-debug
          path: arena_debug.html